"""empty message

Revision ID: d81b86b04514
Revises: ade9f5e44e5d
Create Date: 2025-06-11 13:07:54.797324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81b86b04514'
down_revision: Union[str, None] = 'ade9f5e44e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avocado', sa.Column('probability', sa.DECIMAL(precision=4, scale=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avocado', 'probability')
    # ### end Alembic commands ###
