"""empty message

Revision ID: d971af9d6f22
Revises: f2db53b3f9eb
Create Date: 2025-06-11 12:54:48.897942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd971af9d6f22'
down_revision: Union[str, None] = 'f2db53b3f9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avocado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firmness', sa.DECIMAL(precision=6, scale=1), nullable=False),
    sa.Column('hue', sa.Integer(), nullable=False),
    sa.Column('saturation', sa.Integer(), nullable=False),
    sa.Column('brightness', sa.Integer(), nullable=False),
    sa.Column('color_category', sa.String(), nullable=False),
    sa.Column('sound_db', sa.Integer(), nullable=False),
    sa.Column('weight_g', sa.Integer(), nullable=False),
    sa.Column('size_cm3', sa.Integer(), nullable=False),
    sa.Column('ripeness', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('predict')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predict',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firmness', sa.NUMERIC(precision=6, scale=1), autoincrement=False, nullable=False),
    sa.Column('hue', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('saturation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brightness', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color_category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sound_db', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight_g', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('size_cm3', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ripeness', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('predict_pkey'))
    )
    op.drop_table('avocado')
    # ### end Alembic commands ###
