"""empty message

Revision ID: f2db53b3f9eb
Revises: 
Create Date: 2025-06-10 16:03:14.373322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2db53b3f9eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firmness', sa.DECIMAL(precision=6, scale=1), nullable=False),
    sa.Column('hue', sa.Integer(), nullable=False),
    sa.Column('saturation', sa.Integer(), nullable=False),
    sa.Column('brightness', sa.Integer(), nullable=False),
    sa.Column('color_category', sa.String(), nullable=False),
    sa.Column('sound_db', sa.Integer(), nullable=False),
    sa.Column('weight_g', sa.Integer(), nullable=False),
    sa.Column('size_cm3', sa.Integer(), nullable=False),
    sa.Column('ripeness', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predict')
    # ### end Alembic commands ###
